package com.eds.ctcb.db;

import java.math.BigDecimal;
// default package



/**
 * CashAccount generated by MyEclipse - Hibernate Tools
 */

public class CashAccount  implements java.io.Serializable {


    // Fields    

     private Long accountId;
     private Account account;
     private Currency currency;
     private BigDecimal count;

     

    // Constructors

    /** default constructor */
    public CashAccount() {
    }

    
    /** full constructor */
    public CashAccount(Account account,Currency currency, BigDecimal count) {
        this.account = account;
        this.currency = currency;
        this.count = count;
    }

   
    // Property accessors

  

    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

    public BigDecimal getCount() {
        return this.count;
    }
    
    public void setCount(BigDecimal count) {
        this.count = count;
    }


	public Long getAccountId() {
		return accountId;
	}


	private void setAccountId(Long accountId) {
		this.accountId = accountId;
	}


	public Currency getCurrency() {
		return currency;
	}


	public void setCurrency(Currency currency) {
		this.currency = currency;
	}
   








}