package com.eds.ctcb.db;
// default package

import java.math.BigDecimal;
import java.util.Date;


/**
 * ExchangeRate generated by MyEclipse - Hibernate Tools
 */

public class ExchangeRate  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Currency scurrency;
     private Currency dcurrency;
     private BigDecimal exchangeRate;
     private Date updateTime;


    // Constructors

    /** default constructor */
    public ExchangeRate() {
    }

    
    /** full constructor */
    public ExchangeRate(Currency scurrency, Currency dcurrency, BigDecimal exchangeRate, Date updateTime) {
        this.scurrency = scurrency;
        this.dcurrency = dcurrency;
        this.exchangeRate = exchangeRate;
        this.updateTime = updateTime;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    private void setId(Long id) {
        this.id = id;
    }

    public Currency getScurrency() {
        return this.scurrency;
    }
    
    public void setScurrency(Currency scurrency) {
        this.scurrency = scurrency;
    }

    public Currency getDcurrency() {
        return this.dcurrency;
    }
    
    public void setDcurrency(Currency dcurrency) {
        this.dcurrency = dcurrency;
    }


	public BigDecimal getExchangeRate() {
		return exchangeRate;
	}


	public void setExchangeRate(BigDecimal exchangeRate) {
		this.exchangeRate = exchangeRate;
	}


	public Date getUpdateTime() {
		return updateTime;
	}


	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

   







}