package com.eds.ctcb.db;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * Fund generated by MyEclipse - Hibernate Tools
 */

public class Fund  implements java.io.Serializable {


    // Fields    

	
     private Long id;
     private String name;
     private String code;
     private Currency currency;
     private FundType type;
     private FundCompany company;
     private FundArea area;
     private FundIndustry industry;
     private Integer status;
     private String url;
     private String remark;
    
     
     private Set fundequities = new HashSet(0);


    // Constructors

    /** default constructor */
    public Fund() {
    }

	/** minimal constructor */
    public Fund(String name, String code, Currency currency, FundType type, FundCompany company, FundArea area, FundIndustry industry, Integer status) {
        this.name = name;
        this.code = code;
        this.currency = currency;
        this.type = type;
        this.company = company;
        this.area = area;
        this.industry = industry;
        this.status = status;
    }
    
    /** full constructor */
    public Fund(String name, String code, Currency currency, FundType type, FundCompany company, FundArea area, FundIndustry industry, Integer status, String url, String remark,  Set fundequities) {
        this.name = name;
        this.code = code;
        this.currency = currency;
        this.type = type;
        this.company = company;
        this.area = area;
        this.industry = industry;
        this.status = status;
        this.url = url;
        this.remark = remark;
      
       
        this.fundequities = fundequities;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
   private void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public Currency getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    
    public FundArea getArea() {
		return area;
	}

	public void setArea(FundArea area) {
		this.area = area;
	}

	public FundCompany getCompany() {
		return company;
	}

	public void setCompany(FundCompany company) {
		this.company = company;
	}

	public FundIndustry getIndustry() {
		return industry;
	}

	public void setIndustry(FundIndustry industry) {
		this.industry = industry;
	}

	public FundType getType() {
		return type;
	}

	public void setType(FundType type) {
		this.type = type;
	}

	public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

   

    public Set getFundequities() {
        return this.fundequities;
    }
    
    public void setFundequities(Set fundequities) {
        this.fundequities = fundequities;
    }
   








}