package com.eds.ctcb.db;
// default package



/**
 * Fund generated by MyEclipse - Hibernate Tools
 */

public class FundIndustry  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Fields    

	
     private Long id;
     private String name;
     private String remark;

    // Constructors

    /** default constructor */
    public FundIndustry() {
    }

	/** minimal constructor */
    public FundIndustry(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public FundIndustry(String name, String remark) {
        this.name = name;
        this.remark = remark;
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}