package com.eds.ctcb.db;

// default package

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundEquity generated by MyEclipse - Hibernate Tools
 */

public class FundEquity implements java.io.Serializable {

	// Fields
	

	private Long id;

	private Fund fund;

	
	private Date time;

	private BigDecimal equity;

	private String remark;

	// Constructors

	/** default constructor */
	public FundEquity() {
	}

	/** minimal constructor */
	public FundEquity(Fund fund, Date time, BigDecimal equity) {
		this.fund = fund;
		this.time = time;
		this.equity = equity;
	}

	/** full constructor */
	public FundEquity(Fund fund, Date time, BigDecimal equity, String remark) {
		this.fund = fund;
		this.time = time;
		this.equity = equity;
		this.remark = remark;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	private void setId(Long id) {
		this.id = id;
	}

	public Fund getFund() {
		return this.fund;
	}

	public void setFund(Fund fund) {
		this.fund = fund;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public BigDecimal getEquity() {
		return this.equity;
	}

	public void setEquity(BigDecimal equity) {
		this.equity = equity;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}