package com.eds.ctcb.db;
// default package

import java.util.Date;


/**
 * Holiday generated by MyEclipse - Hibernate Tools
 */

public class Holiday  implements java.io.Serializable {


    // Fields    

	
	
     private Long id;
     private Date day;
     private Integer state;


    // Constructors

    /** default constructor */
    public Holiday() {
    }

	/** minimal constructor */
    public Holiday(Date day) {
        this.day = day;
    }
    
    /** full constructor */
    public Holiday(Date day, Integer state) {
        this.day = day;
        this.state = state;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }
   








}