package com.eds.ctcb.db;
// default package

import java.util.HashSet;
import java.util.Set;



/**
 * Location generated by MyEclipse - Hibernate Tools
 */

public class Location  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String url;
     private String remark;
     private Set<ResourceLocation> resourceLocations = new HashSet<ResourceLocation>(0);


    // Constructors

    /** default constructor */
    public Location() {
    }

	/** minimal constructor */
    public Location(Long id, String url) {
        this.id = id;
        this.url = url;
    }
    
    /** full constructor */
    public Location(Long id, String url, String remark, Set<ResourceLocation> resourceLocations) {
        this.id = id;
        this.url = url;
        this.remark = remark;
        this.resourceLocations = resourceLocations;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Set<ResourceLocation> getResourceLocations() {
        return this.resourceLocations;
    }
    
    public void setResourceLocations(Set<ResourceLocation> resourceLocations) {
        this.resourceLocations = resourceLocations;
    }
   








}