package com.eds.ctcb.db;
// default package

import java.util.Date;



/**
 * Log generated by MyEclipse - Hibernate Tools
 */

public class Log  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Integer type;
     private User user;
     private Date time;
     private String content;


    // Constructors

    /** default constructor */
    public Log() {
    }

	/** minimal constructor */
    public Log(Integer type, User user, Date time) {
        this.type = type;
        this.user = user;
        this.time = time;
    }
    
    /** full constructor */
    public Log(Integer type, User user, Date time, String content) {
        this.type = type;
        this.user = user;
        this.time = time;
        this.content = content;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

  
    public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
   








}