package com.eds.ctcb.db;
// default package

import java.util.Date;


/**
 * RankSet generated by MyEclipse - Hibernate Tools
 */

public class RankSet  implements java.io.Serializable {

	

    // Fields    

     private Long id;
     private Integer year;
     private Integer quarter;
     private String topic;
     private Date createTime;
     private String remark;


    // Constructors

    /** default constructor */
    public RankSet() {
    }

	/** minimal constructor */
    public RankSet(String topic, Date createTime) {
        this.topic = topic;
        this.createTime = createTime;
    }
    
    /** full constructor */
    public RankSet(Integer year, Integer quarter, String topic, Date createTime, String remark) {
        this.year = year;
        this.quarter = quarter;
        this.topic = topic;
        this.createTime = createTime;
        this.remark = remark;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

   
    public Integer getQuarter() {
		return quarter;
	}

	public void setQuarter(Integer quarter) {
		this.quarter = quarter;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }

   

    public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
}