package com.eds.ctcb.db;
// default package

import java.util.HashSet;
import java.util.Set;


/**
 * ReportInfo generated by MyEclipse - Hibernate Tools
 */

public class ReportInfo  implements java.io.Serializable {


    // Fields    

     private Long id;
     
     private Integer year;
     private Integer quarter;
     private String topic;
     
     private String remark;
    // private Set reportdatas ;


    // Constructors

    /** default constructor */
    public ReportInfo() {
    }

	/** minimal constructor */
    public ReportInfo(Integer year, Integer quarter, String topic) {
        this.year = year;
        this.quarter = quarter;
        this.topic = topic;
    }
    
    /** full constructor */
    public ReportInfo(Integer year, Integer quarter, String topic, String remark) {
        this.year = year;
        this.quarter = quarter;
        this.topic = topic;
        this.remark = remark;
       // this.reportdatas = reportdatas;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    

    public Integer getQuarter() {
		return quarter;
	}

	public void setQuarter(Integer quarter) {
		this.quarter = quarter;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /*
	public Set getReportdatas() {
		return reportdatas;
	}

	public void setReportdatas(Set reportdatas) {
		this.reportdatas = reportdatas;
	}
*/

   








}