package com.eds.ctcb.db;

import java.math.BigDecimal;
// default package

import com.eds.ctcb.bean.FundPerformance;



/**
 * ReportData generated by MyEclipse - Hibernate Tools
 */

public class ReportData  implements Comparable,java.io.Serializable {


    // Fields    

     public int compareTo(Object o) {
    	 ReportData obj = (ReportData) o;
 		if(this.incomingRate.compareTo(obj.getIncomingRate())>0){
 			return 1;
 		} else if(this.incomingRate.compareTo(obj.getIncomingRate())==0){
 			if(this.id.compareTo(obj.getId())>0){
 				return 1;
 			}else if(this.id.compareTo(obj.getId())==0){
 				return 0;
 				
 			}else{
 				return -1;
 			}
 					
 		}else{
 			return -1;
 		}
 		
	}


	private Long id;
     private User user;
     private ReportInfo reportInfo;
     private Integer rank;
     private BigDecimal startEquity;
     private BigDecimal endEquity;
     private BigDecimal incoming;
     private Float incomingRate;


    // Constructors

    /** default constructor */
    public ReportData() {
    }

    
    /** full constructor */
    public ReportData(User user, ReportInfo reportInfo, Integer rank, BigDecimal startEquity, BigDecimal endEquity, BigDecimal incoming, Float incomingRate) {
        this.user = user;
        this.reportInfo = reportInfo;
        this.rank = rank;
        this.startEquity = startEquity;
        this.endEquity = endEquity;
        this.incoming = incoming;
        this.incomingRate = incomingRate;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    

	public BigDecimal getIncoming() {
		return incoming;
	}


	public void setIncoming(BigDecimal incoming) {
		this.incoming = incoming;
	}


	

	public Integer getRank() {
		return rank;
	}


	public void setRank(Integer rank) {
		this.rank = rank;
	}


	public BigDecimal getEndEquity() {
		return endEquity;
	}


	public void setEndEquity(BigDecimal endEquity) {
		this.endEquity = endEquity;
	}


	public Float getIncomingRate() {
		return incomingRate;
	}


	public void setIncomingRate(Float incomingRate) {
		this.incomingRate = incomingRate;
	}


	public ReportInfo getReportInfo() {
		return reportInfo;
	}


	public void setReportInfo(ReportInfo reportInfo) {
		this.reportInfo = reportInfo;
	}


	public BigDecimal getStartEquity() {
		return startEquity;
	}


	public void setStartEquity(BigDecimal startEquity) {
		this.startEquity = startEquity;
	}


	

   
   








}