package com.eds.ctcb.db;

// default package

import java.util.HashSet;
import java.util.Set;

/**
 * Resource generated by MyEclipse - Hibernate Tools
 */


public class Resource implements java.io.Serializable {

	// Fields

	private Long id;

	private String name;

	private String remark;

	private Long parentId;

	private Long type;

	private Set<ResourceLocation> resourceLocations = new HashSet<ResourceLocation>(0);

	private Set<RoleResource> roleResources = new HashSet<RoleResource>(0);

	// Constructors

	/** default constructor */
	public Resource() {
	}

	/** minimal constructor */
	public Resource(Long id, String name, Long type) {
		this.id = id;
		this.name = name;
		this.type = type;
	}

	/** full constructor */
	public Resource(Long id, String name, String remark, Long parentId,
			Long type, Set<ResourceLocation> resourceLocations, Set<RoleResource> roleResources) {
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.parentId = parentId;
		this.type = type;
		this.resourceLocations = resourceLocations;
		this.roleResources = roleResources;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Set<ResourceLocation> getResourceLocations() {
		return this.resourceLocations;
	}

	public void setResourceLocations(Set<ResourceLocation> resourceLocations) {
		this.resourceLocations = resourceLocations;
	}

	public Set<RoleResource> getRoleResources() {
		return this.roleResources;
	}

	public void setRoleResources(Set<RoleResource> roleResources) {
		this.roleResources = roleResources;
	}

}