package com.eds.ctcb.db;

// default package

/**
 * RoleResource generated by MyEclipse - Hibernate Tools
 */

public class RoleResource implements java.io.Serializable {

	// Fields

	private Long id;

	private Role role;

	private Resource resource;

	// Constructors

	/** default constructor */
	public RoleResource() {
	}

	/** full constructor */
	public RoleResource(Long id, Role role, Resource resource) {
		this.id = id;
		this.role = role;
		this.resource = resource;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

}