package com.eds.ctcb.db;

// default package

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by MyEclipse - Hibernate Tools
 */

public class Role implements java.io.Serializable {

	// Fields

	private Long id;

	private String name;

	private String remark;

	private Set<RoleResource> roleResources = new HashSet<RoleResource>(0);

	private Set<UserRole> userRoles = new HashSet<UserRole>();

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** minimal constructor */
	public Role(Long id, String name) {
		this.id = id;
		this.name = name;
	}

	/** full constructor */
	public Role(Long id, String name, String remark, Set<RoleResource> roleResources,
			Set<UserRole> userRoles) {
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.roleResources = roleResources;
		this.userRoles = userRoles;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<RoleResource> getRoleResources() {
		return this.roleResources;
	}

	public void setRoleResources(Set<RoleResource> roleResources) {
		this.roleResources = roleResources;
	}

	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

}