package com.eds.ctcb.db;

// default package

import java.math.BigDecimal;
import java.util.Date;

/**
 * SavingPlan generated by MyEclipse - Hibernate Tools
 */

public class SavingPlan implements java.io.Serializable {

	// Fields

  
  private Long id;

	private Account account;

	private Integer tradeType;

	private Fund fund;

	private Date createTime;

	private Date updateTime;

	private BigDecimal count;
	
	private Currency currency;

	private Integer day;

	private Float incomingSet;

	private BigDecimal rate;

	private Integer status;

	// Constructors

	/** default constructor */
	public SavingPlan() {
	}

	/** minimal constructor */
	public SavingPlan(Account account, Fund fund, Date updateTime, BigDecimal count, Currency currency,
			Integer day, Float incomingset, Integer status) {
		this.account = account;
		this.fund = fund;
		this.updateTime = updateTime;
		this.count = count;
		this.currency = currency;
		this.day = day;
		this.incomingSet = incomingSet;
		this.status = status;
	}

	/** full constructor */
	public SavingPlan(Account account, Fund fund, Date createTime,
			Date updateTime, BigDecimal count, Integer day, Float incomingSet,
			BigDecimal rate, Integer status) {
		this.account = account;
		this.fund = fund;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.count = count;
		this.day = day;
		this.incomingSet = incomingSet;
		this.rate = rate;
		this.status = status;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Fund getFund() {
		return this.fund;
	}

	public void setFund(Fund fund) {
		this.fund = fund;
	}

	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}
	
	public Currency getCurrency() {
		return currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getDay() {
		return day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	public Float getIncomingSet() {
		return incomingSet;
	}

	public void setIncomingSet(Float incomingSet) {
		this.incomingSet = incomingSet;
	}

	public BigDecimal getRate() {
		return rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public Integer getTradeType() {
		return tradeType;
	}

	public void setTradeType(Integer tradeType) {
		this.tradeType = tradeType;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
}