package com.eds.ctcb.db;

// default package

import java.util.Date;

/**
 * TimerTask generated by MyEclipse - Hibernate Tools
 */

public class TimerTask implements java.io.Serializable {

	// Fields

	private Long id;

	private Integer taskType;

	private Date createTime;

	private Integer taskCount;

	private Integer status;
	
	private String content;

	// Constructors

	/** default constructor */
	public TimerTask() {
	}

	/** full constructor */
	public TimerTask(Integer taskType, Date createTime, Integer taskCount,
			Integer status, String content) {
		this.taskType = taskType;
		this.createTime = createTime;
		this.taskCount = taskCount;
		this.status = status;
		this.content = content;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getTaskCount() {
		return taskCount;
	}

	public void setTaskCount(Integer taskCount) {
		this.taskCount = taskCount;
	}

	public Integer getTaskType() {
		return taskType;
	}

	public void setTaskType(Integer taskType) {
		this.taskType = taskType;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}