package com.eds.ctcb.db;

//default package

import java.math.BigDecimal;
import java.util.Date;

/**
 * Trade generated by MyEclipse - Hibernate Tools
 */

public class Trade implements java.io.Serializable {

	// Fields

	private Long id;

	private Account accountBySaccountId;

	private User tradeUser;

	private Account accountByDaccountId;

	private Integer type;

	private Integer tradeMode;

	private BigDecimal count;
	
	private Currency currency;

	private Float incomingSet;

	private Date createTime;

	private Integer status;

	private Date setTime;

	private Date tradeTime;

	
	private BigDecimal fee;

	private TradeTask tradeTask;

	// Constructors

	/** default constructor */
	public Trade() {
	}

	/** minimal constructor */
	public Trade(Account accountBySaccountId, User tradeUser,
			Account accountByDaccountId, Integer type, Date createIime,
			Integer status, Date setTime) {
		this.accountBySaccountId = accountBySaccountId;
		this.tradeUser = tradeUser;
		this.accountByDaccountId = accountByDaccountId;
		this.type = type;
		this.createTime = createIime;
		this.status = status;
		this.setTime = setTime;
	}

	/** full constructor */
	public Trade(Account accountBySaccountId, User tradeUser,
			Account accountByDaccountId, Integer type, Integer tradeMode,
			BigDecimal count, Currency currency, Float incomingSet, Date createTime,
			Integer status, Date setTime, Date tradeTime, BigDecimal fee,
			TradeTask tradeTask) {
		this.accountBySaccountId = accountBySaccountId;
		this.tradeUser = tradeUser;
		this.accountByDaccountId = accountByDaccountId;
		this.type = type;
		this.tradeMode = tradeMode;
		this.count = count;
		this.currency = currency;
		this.incomingSet = incomingSet;
		this.createTime = createTime;
		this.status = status;
		this.setTime = setTime;
		this.tradeTime = tradeTime;
		this.fee = fee;
		this.tradeTask = tradeTask;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	private void setId(Long id) {
		this.id = id;
	}

	

	public User getTradeUser() {
		return tradeUser;
	}

	public void setTradeUser(User tradeUser) {
		this.tradeUser = tradeUser;
	}

	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	public Currency getCurrency() {
		return currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getSetTime() {
		return setTime;
	}

	public void setSetTime(Date setTime) {
		this.setTime = setTime;
	}

	public Account getAccountByDaccountId() {
		return accountByDaccountId;
	}

	public void setAccountByDaccountId(Account accountByDaccountId) {
		this.accountByDaccountId = accountByDaccountId;
	}

	public Account getAccountBySaccountId() {
		return accountBySaccountId;
	}

	public void setAccountBySaccountId(Account accountBySaccountId) {
		this.accountBySaccountId = accountBySaccountId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public BigDecimal getFee() {
		return fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public Float getIncomingSet() {
		return incomingSet;
	}

	public void setIncomingSet(Float incomingSet) {
		this.incomingSet = incomingSet;
	}

	public Integer getTradeMode() {
		return tradeMode;
	}

	public void setTradeMode(Integer tradeMode) {
		this.tradeMode = tradeMode;
	}

	public TradeTask getTradeTask() {
		return tradeTask;
	}

	public void setTradeTask(TradeTask tradeTask) {
		this.tradeTask = tradeTask;
	}

	public Date getTradeTime() {
		return tradeTime;
	}

	public void setTradeTime(Date tradeTime) {
		this.tradeTime = tradeTime;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}