package com.eds.ctcb.db;
// default package

import java.util.Date;


/**
 * TradeTime generated by MyEclipse - Hibernate Tools
 */

public class TradeTime  implements java.io.Serializable {


    // Fields    
	

     private Long id;
     private Integer tradeType;
     private Integer fundArea;
     private Integer fundType;
     private Long fundId;
     private Date beginTime;
     private Date endTime;


    // Constructors

    /** default constructor */
    public TradeTime() {
    }

    
    /** full constructor */
    public TradeTime(Integer tradeType, Integer fundArea, Integer fundType, Long fundId, Date beginTime, Date endTime) {
    	this.tradeType = tradeType;
    	this.fundArea = fundArea;
        this.fundType = fundType;
        this.fundId = fundId;
        this.beginTime = beginTime;
        this.endTime = endTime;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }


	public Date getBeginTime() {
		return beginTime;
	}


	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}


	public Date getEndTime() {
		return endTime;
	}


	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}


	public Integer getFundArea() {
		return fundArea;
	}


	public void setFundArea(Integer fundArea) {
		this.fundArea = fundArea;
	}


	public Long getFundId() {
		return fundId;
	}


	public void setFundId(Long fundId) {
		this.fundId = fundId;
	}


	public Integer getFundType() {
		return fundType;
	}


	public void setFundType(Integer fundType) {
		this.fundType = fundType;
	}


	public Integer getTradeType() {
		return tradeType;
	}


	public void setTradeType(Integer tradeType) {
		this.tradeType = tradeType;
	}

    
   








}