package com.eds.ctcb.db;
//default package

import java.util.Date;


/**
 * TradeTask generated by MyEclipse - Hibernate Tools
 */

public class TradeTask  implements java.io.Serializable {


    // Fields    
	

     private Long id;
     private Trade trade;
     private Date createTime;
     private Date planTime;
     private Integer status;
     private Integer count;
     private Date lastTime;
     private String remark;


    // Constructors

    /** default constructor */
    public TradeTask() {
    }

	/** minimal constructor */
    public TradeTask(Trade trade, Date createTime, Date planTime, Integer status) {
        this.trade = trade;
        this.createTime = createTime;
        this.planTime = planTime;
        this.status = status;
    }
    
    /** full constructor */
    public TradeTask(Trade trade, Date createTime, Date planTime, Integer status, Integer count, Date lastTime) {
        this.trade = trade;
        this.createTime = createTime;
        this.planTime = planTime;
        this.status = status;
        this.count = count;
        this.lastTime = lastTime;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    private void setId(Long id) {
        this.id = id;
    }

    public Trade getTrade() {
        return this.trade;
    }
    
    public void setTrade(Trade trade) {
        this.trade = trade;
    }

  

    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastTime() {
		return lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	public Date getPlanTime() {
		return planTime;
	}

	public void setPlanTime(Date planTime) {
		this.planTime = planTime;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

   
   








}