package com.eds.ctcb.db;
// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * User generated by MyEclipse - Hibernate Tools
 */

public class User  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String userName;
     private String password;
     private Date createTime;
     private String name;
     private Integer sex;
     private String company;
     private String address;
     private String post;
     private String email;
     private String phone;
     private Integer status;
     private String remark;
     private String addition;
     private Set<Account> accounts = new HashSet<Account>(0);
     //private Set reportdatas = new HashSet(0);
     private Set<UserRole> userRoles = new HashSet<UserRole>();
     //private Set trades = new HashSet(0);


    // Constructors

    /** default constructor */
    public User() {
    }

	/** minimal constructor */
    public User(String userName, String password, Date createTime, Integer status) {
        this.userName = userName;
        this.password = password;
        this.createTime = createTime;
        this.status = status;
    }
    
    /** full constructor */
    public User(String userName, String password, Date createTime, String name, Integer sex, String company, String address, String post, String email, String phone, Integer status, String remark, String addition, Set<Account> accounts, Set<UserRole> userRoles) {
        this.userName = userName;
        this.password = password;
        this.createTime = createTime;
        this.name = name;
        this.sex = sex;
        this.company = company;
        this.address = address;
        this.post = post;
        this.email = email;
        this.phone = phone;
        this.status = status;
        this.remark = remark;
        this.addition = addition;
        this.accounts = accounts;
        //this.reportdatas = reportdatas;
       // this.userRoles = userRoles;
       // this.trades = trades;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

  

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

   

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

   

    public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAddition() {
        return this.addition;
    }
    
    public void setAddition(String addition) {
        this.addition = addition;
    }

    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }
    
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }
    /*
    public Set getReportdatas() {
        return this.reportdatas;
    }
    
    public void setReportdatas(Set reportdatas) {
        this.reportdatas = reportdatas;
    }

   
    

    public Set getTrades() {
        return this.trades;
    }
    
    public void setTrades(Set trades) {
        this.trades = trades;
    }
   */








}