package com.eds.ctcb.db;

// default package

/**
 * UserRole generated by MyEclipse - Hibernate Tools
 */

public class UserRole implements java.io.Serializable {

	// Fields

	private Long id;

	private User user;

	private Role role;

	// Constructors

	/** default constructor */
	public UserRole() {
	}

	/** full constructor */
	public UserRole(Long id, User user, Role role) {
		this.id = id;
		this.user = user;
		this.role = role;
	}

	// Property accessors

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}